name : PR Quality Gate (Cypress Tests + Eslint) # Workflow name
on : # Trigger the workflow on pull request and push events to the main branch
    pull_request: # Trigger on pull request events
        branches: # Specify the branches to trigger the workflow on pull request events
            - main # trigger the workflow on pull requests to the main branch
    push: # Trigger on push events
        branches: # Specify the branches to trigger the workflow on push events
            - main # trigger the workflow on push to the main branch
jobs : # Define the jobs to run in the workflow
    lint_and_test: # Job name
        name: Eslint and Cypress Tests # name of the job
        runs-on: ubuntu-latest # specify the operating system to run the job on

        steps:
            - name: Checkout code # Step name
              uses: actions/checkout@v4 # checkout the code from the repository

            - name: Remove BOM from package.json # Step name
              run: sed -i 's/^\xef\xbb\xbf//' package.json # remove the unnecessary BOM character from package.json file
            
            - name: Set up Node.js # Step name
              uses: actions/setup-node@v4 # why we are using setup-node action? to set up the Node.js environment for the workflow
              with: # specify the Node.js version to use
                  node-version: '20' # use Node.js version 20

            - name: Install dependencies # Step name
              run: |
                npm ci # install the dependencies using npm ci command
                npm install eslint --save-dev # Ensure eslint is installed

            - name: Run Eslint # Step name
              run: npx eslint . # run the Eslint command to lint the code

            - name: Run Cypress Tests # Step name
              uses: cypress-io/github-action@v6 # use the cypress-io/github-action to run the Cypress tests
              with: # specify the browser to run the tests on
                browser: chrome # run the tests on Chrome browser

            - name: Execute Cypress Tests # Step name
              run: npx cypress run # run the Cypress tests using npx cypress run command
            

            - name: Upload Cypress Artifacts # Step name
              if: failure() # if the Cypress tests fail, upload the screenshots and videos as artifacts
              uses: actions/upload-artifact@v4 # to upload the artifacts to the GitHub Actions workflow
              with: # specify the name and path of the artifacts to upload
                name: cypress-artifacts # name of the artifact to upload
                path: cypress/screenshots, cypress/videos # path of the screenshots and videos to upload as artifacts